services:
  app:
    build:
      context: .docker
      dockerfile: Dockerfile
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      XDEBUG_ENABLED: ${XDEBUG_ENABLED:-false}
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  fe:
    image: node:22-bookworm
    working_dir: /var/www/html
    environment:
      TZ: ${APP_TIMEZONE:-UTC}
    volumes:
      - ./:/var/www/html
    entrypoint: ./.docker/config/node/entrypoint.sh
    user: "33:33"
    ports:
      - "5173:5173"
    healthcheck:
      test: [ "CMD-SHELL", "node --version" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:17.7-bookworm
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      TZ: ${APP_TIMEZONE:-UTC}
    ports:
      - "5432:5432"
    volumes:
      - db17.7:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-laravel}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4-bookworm
    environment:
      TZ: ${APP_TIMEZONE:-UTC}
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  mailcatcher:
    image: dockage/mailcatcher:0.9
    environment:
      TZ: UTC
    ports:
      - "1080:1080"
    healthcheck:
      test: [ "CMD", "echo", "-n", "EHLO healthcheck", "|", "nc", "localhost", "25" ]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db17.7:
